### ISSUE TITLE
Emitting changed rooms

### ISSUE THREAD

**Issue by anilgulecha** [yjs/y-websocket#18]
We're using yjs-websocket as a centralized sync layer for prosemirror collaboration. This is essential a cache of the latest (online) state, and not the final store.

I would like to pass a HTTP endpoint, which is a callback-endpoint triggered with the room-id. (this will technically be a publish endpoint, and applications can then implement their own subscription and do other actions based on this).

I can work with @Mansehej to build a patch, so CALLBACK_SERVER env variable can be setup, and called. Additionally CALLBACK_TIMEOUT can be configured, as well as CALLBACK_DEBOUNCE_TIME. Failed/timeout response will not be retried.

This could also be achieved with integrating with proper pub/sub services, but it seems like a HTTP based callback is the best/broadest way of building this to be used by a host of applications.

Will such a PR be in the scope of the project. (I envision it will go well with persistent state - it'll make yjs websocket a good cache store, and suitable for offline-first applications)

**Comment by dmonad** [comment]
Hey @anilgulecha ,

thanks for the offer! I'd love to have an example that will show how this works. I'd like to keep y-websocket minimalistic, so I think it would be best if your example would be implemented in a separate demo project. We could also include it in [yjs-demos](https://github.com/yjs/yjs-demos/)

**Comment by anilgulecha** [comment]
We've almost completed building this. The approach has been to add callback.js, and add opt-in environment variables (akin to YPERSISTENCE today), that turns on this behavior.

I think the y-websokcet layer is the best place to add it in - it's where it would be of use to people who choose to use it. but if you would recommend implementing this another way, we can do that too. The PR will be opened today/tomorrow.

**Comment by mikkorantalainen** [comment]
I'm interested to see more info about this, too. I, too, think that base y-websocket should be kept minimalistic but it would be great to have lots of documentation and demos about how to do more complex stuff.

From all the collaborative text editors I've seen, it seems that Yjs + atlaskit combination has been the only system that doesn't have any broken edge cases plus its performance (=latency) is really good. However, to use it in real production it needs redundant server support, authentication and persistence. The redundant server support might be part of the base y-websocket in long run, if custom implementation could do better work than using some external packages for that part. However, in my opinion, authentication and persistence should be kept as external parts in the future, too, because different use cases need different implementations for those parts in any case.

**Comment by dmonad** [comment]
@mikkorantalainen Seriously, if you find any bugs, report them! I'll fix them :wink:

**Comment by dmonad** [comment]
Released in `y-websocket@1.3.2`
